baseurl: /uppervalley
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: uppervalley
github_org: maptime
maptime:
  chapter: MaptimeUV
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
